basePath: /api/annoucements
consumes:
- application/json
definitions:
  forms.AnnoucementForm:
    properties:
      annoucement:
        example: This is a annoucement!
        minLength: 1
        type: string
      files:
        example:
        - 6376c8283cc695e19d785b08
        items:
          type: string
        type: array
    required:
    - annoucement
    type: object
  models.AnnoucementWLookUp:
    description: Annoucement of home
    properties:
      _id:
        example: 6376c8283cc695e19d785b08
        type: string
      annoucement:
        example: This is a annoucement!
        type: string
      files:
        items:
          $ref: '#/definitions/models.File'
        type: array
        x-omitempty: true
      update_date:
        example: "2022-09-21T20:10:23.309+00:00"
        type: string
      upload_date:
        example: "2022-09-21T20:10:23.309+00:00"
        type: string
      user:
        $ref: '#/definitions/models.SimpleUser'
    type: object
  models.File:
    description: File attached to annoucement
    properties:
      _id:
        example: 6376c8283cc695e19d785b08
        type: string
      title:
        example: Title
        type: string
      type:
        example: private
        type: string
    type: object
  models.SimpleUser:
    description: User account information . Global model for all users
    properties:
      _id:
        example: 6376c8283cc695e19d785b08
        type: string
      first_lastname:
        example: Firstlastname
        type: string
      name:
        example: Name
        type: string
      rut:
        example: 12345678-0
        type: string
        x-omitempty: true
      second_lastname:
        example: Secondlastname
        type: string
    type: object
  res.Response:
    properties:
      body:
        additionalProperties: true
        type: object
        x-omitempty: true
      message:
        example: Error message
        type: string
        x-omitempty: true
      success:
        type: boolean
    type: object
  smaps.AnnoucementsMap:
    properties:
      annoucements:
        items:
          $ref: '#/definitions/models.AnnoucementWLookUp'
        type: array
      total:
        type: integer
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API Server For home annoucements in Intranet
  license:
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Annoucement API
  version: "1.0"
paths:
  /delete_annoucement/{idAnnoucement}:
    delete:
      consumes:
      - application/json
      description: Delete a annoucement in home, ROLS=[Director,Directive]
      parameters:
      - description: MongoID Annoucement
        in: path
        name: idAnnoucement
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/res.Response'
        "400":
          description: idAnnoucement Must be a MongoID
          schema:
            $ref: '#/definitions/res.Response'
        "401":
          description: Unauthorized role
          schema:
            $ref: '#/definitions/res.Response'
        "503":
          description: Service Unavailable - NATS || DB Service Unavailable
          schema:
            $ref: '#/definitions/res.Response'
      summary: Delete annoucement
      tags:
      - annoucements
  /get_annoucements:
    get:
      consumes:
      - application/json
      description: Get genneral annoucements
      parameters:
      - default: 0
        description: int valid >= 0
        in: query
        name: skip
        type: integer
      - default: 20
        description: int valid >= 0
        in: query
        maximum: 20
        name: limit
        type: integer
      - default: false
        description: total length data
        in: query
        name: total
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            allOf:
            - $ref: '#/definitions/res.Response'
            - properties:
                body:
                  $ref: '#/definitions/smaps.AnnoucementsMap'
              type: object
        "400":
          description: Limit must be a int
          schema:
            $ref: '#/definitions/res.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/res.Response'
        "503":
          description: Service Unavailable - NATS || Mongo Service Unavailable
          schema:
            $ref: '#/definitions/res.Response'
      summary: Get annoucements of home
      tags:
      - annoucements
  /upload_annoucement:
    post:
      consumes:
      - application/json
      description: Upload a annoucement in home, ROLS=[Director,Directive]
      parameters:
      - description: Add annoucement - Files must be MongoId[]
        in: body
        name: annoucement
        required: true
        schema:
          $ref: '#/definitions/forms.AnnoucementForm'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/res.Response'
        "400":
          description: Bad request - Bad body
          schema:
            $ref: '#/definitions/res.Response'
        "401":
          description: Unauthorized role
          schema:
            $ref: '#/definitions/res.Response'
        "409":
          description: Todos los archivos a publicar deben ser públicos
          schema:
            $ref: '#/definitions/res.Response'
        "500":
          description: Server Internal Error - Maybe a bad response of NATS
          schema:
            $ref: '#/definitions/res.Response'
        "503":
          description: Service Unavailable - NATS || DB Service Unavailable
          schema:
            $ref: '#/definitions/res.Response'
      summary: Upload annoucement in home
      tags:
      - annoucements
produces:
- application/json
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    description: BearerJWTToken in Authorization Header
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
tags:
- description: Unique tag - Annoucements of home
  name: annoucements
